//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.0.27.0 (Newtonsoft.Json v12.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------





export class ReceiptOfGoods implements IReceiptOfGoods {
    receiptOfGoodsId!: string;
    receiptOfGoodsNumber!: number;
    purchaseOrderId!: string;
    purchaseOrderReference!: string;
    purchaseOrderNumber!: number;
    vendorId!: string;
    /** Shipping Address */
    shippingAddress!: ShippingAddress;
    receiptOfGoodsItems!: ReceiptOfGoodsItems[];

    constructor(data?: IReceiptOfGoods) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.receiptOfGoodsId = _data["receipt-of-goods-id"];
            this.receiptOfGoodsNumber = _data["receipt-of-goods-number"];
            this.purchaseOrderId = _data["purchase-order-id"];
            this.purchaseOrderReference = _data["purchase-order-reference"];
            this.purchaseOrderNumber = _data["purchase-order-number"];
            this.vendorId = _data["vendor-id"];
            this.shippingAddress = _data["shipping-address"] ? ShippingAddress.fromJS(_data["shipping-address"]) : <any>undefined;
            if (Array.isArray(_data["receipt-of-goods-items"])) {
                this.receiptOfGoodsItems = [] as any;
                for (let item of _data["receipt-of-goods-items"])
                    this.receiptOfGoodsItems!.push(ReceiptOfGoodsItems.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ReceiptOfGoods {
        data = typeof data === 'object' ? data : {};
        let result = new ReceiptOfGoods();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["receipt-of-goods-id"] = this.receiptOfGoodsId;
        data["receipt-of-goods-number"] = this.receiptOfGoodsNumber;
        data["purchase-order-id"] = this.purchaseOrderId;
        data["purchase-order-reference"] = this.purchaseOrderReference;
        data["purchase-order-number"] = this.purchaseOrderNumber;
        data["vendor-id"] = this.vendorId;
        data["shipping-address"] = this.shippingAddress ? this.shippingAddress.toJSON() : <any>undefined;
        if (Array.isArray(this.receiptOfGoodsItems)) {
            data["receipt-of-goods-items"] = [];
            for (let item of this.receiptOfGoodsItems)
                data["receipt-of-goods-items"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IReceiptOfGoods {
    receiptOfGoodsId: string;
    receiptOfGoodsNumber: number;
    purchaseOrderId: string;
    purchaseOrderReference: string;
    purchaseOrderNumber: number;
    vendorId: string;
    /** Shipping Address */
    shippingAddress: ShippingAddress;
    receiptOfGoodsItems: ReceiptOfGoodsItems[];
}

export class ShippingAddress implements IShippingAddress {
    name!: string;
    street!: string;
    city!: string;
    country!: string;

    constructor(data?: IShippingAddress) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.street = _data["street"];
            this.city = _data["city"];
            this.country = _data["country"];
        }
    }

    static fromJS(data: any): ShippingAddress {
        data = typeof data === 'object' ? data : {};
        let result = new ShippingAddress();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["street"] = this.street;
        data["city"] = this.city;
        data["country"] = this.country;
        return data; 
    }
}

export interface IShippingAddress {
    name: string;
    street: string;
    city: string;
    country: string;
}

export class ReceiptOfGoodsItems implements IReceiptOfGoodsItems {
    sku!: string;
    itemId!: string;
    quantity!: number;
    unitPrice!: number;

    constructor(data?: IReceiptOfGoodsItems) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.sku = _data["sku"];
            this.itemId = _data["item-id"];
            this.quantity = _data["quantity"];
            this.unitPrice = _data["unit-price"];
        }
    }

    static fromJS(data: any): ReceiptOfGoodsItems {
        data = typeof data === 'object' ? data : {};
        let result = new ReceiptOfGoodsItems();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["sku"] = this.sku;
        data["item-id"] = this.itemId;
        data["quantity"] = this.quantity;
        data["unit-price"] = this.unitPrice;
        return data; 
    }
}

export interface IReceiptOfGoodsItems {
    sku: string;
    itemId: string;
    quantity: number;
    unitPrice: number;
}