/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PurchaseOrderId = string;
export type ReferenceNumber = string;
export type PurchaseOrderNumber = number;
export type VendorId = string;
export type Name = string;
export type Street = string;
export type City = string;
export type Country = string;
export type SKU = string;
export type ItemId = string;
export type Quantity = number;
export type UnitPrice = number;

export interface PurchaseOrder {
  purchaseOrderId: PurchaseOrderId;
  purchaseOrderReference: ReferenceNumber;
  purchaseOrderNumber: PurchaseOrderNumber;
  vendorId: VendorId;
  shippingAddress: Address;
  billingAddress: Address1;
  purchaseOrderItems: Item[];
}
/**
 * Shipping Address
 */
export interface Address {
  name: Name;
  street: Street;
  city: City;
  country: Country;
}
/**
 * Billing Address
 */
export interface Address1 {
  name: Name;
  street: Street;
  city: City;
  country: Country;
}
export interface Item {
  sku: SKU;
  itemId: ItemId;
  quantity: Quantity;
  unitPrice: UnitPrice;
}
