name: Build

on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
defaults:
  run:
    shell: bash
jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install net7.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Nuget Configure Package Source
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://nuget.pkg.github.com/thefringeninja/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: ghcr login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Compile
      run: |
        dotnet build --configuration release
    - name: Test
      run: |
        dotnet test --configuration release --framework=net7.0 \
          --logger:html --logger:"console;verbosity=normal" \
          --results-directory=$(pwd)/.test-results
    - name: Publish Test Results
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        path: .test-results/
        name: test-results
